// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CategoryFilterController from "./category_filter_controller"
application.register("category-filter", CategoryFilterController)

import ConfirmController from "./confirm_controller"
application.register("confirm", ConfirmController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import SummaryController from "./summary_controller"
application.register("summary", SummaryController)

import ToggleController from "./toggle_controller"
application.register("toggle", ToggleController)
