// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ConfirmController from "./confirm_controller"
application.register("confirm", ConfirmController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import SummaryController from "./summary_controller"
application.register("summary", SummaryController)

import ToggleController from "./toggle_controller"
application.register("toggle", ToggleController)

import AvatarPreviewController from "./avatar_preview_controller"
application.register("avatar-preview", AvatarPreviewController)

import AutocompleteController from "./autocomplete_controller"
application.register("autocomplete", AutocompleteController)

import HomeAutocompleteController from "./home_autocomplete_controller"
application.register("home-autocomplete", HomeAutocompleteController)

import ShoppingAutocompleteController from "./shopping_autocomplete_controller"
application.register("shopping-autocomplete", ShoppingAutocompleteController)

import PriceRecordAutocompleteController from "./price_record_autocomplete_controller"
application.register("price-record-autocomplete", PriceRecordAutocompleteController)

import LoadingController from "./loading_controller"
application.register("loading", LoadingController)

import CopyController from "./copy_controller"
application.register("copy", CopyController)

import SidebarController from "./sidebar_controller"
application.register("sidebar", SidebarController)

import StatsAutocompleteController from "./stats_autocomplete_controller"
application.register("stats-autocomplete", StatsAutocompleteController)

import PriceChartController from "./price_chart_controller"
application.register("price-chart", PriceChartController)
